version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - node/install
      - run: node --version
      - run: npm version
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build/*
  prepare:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - attach_workspace:
         at: .
      - run:
          name: Get gh-pages
          command: |
            git clone -b gh-pages https://github.com/shopizer-ecommerce/documentation.git .

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      #- prepare:
      #    requires:
      #      - build