version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run: node --version
      - run: npm version
      - run: npm install
      - run: npm run build
      - run: ls -lR 
      - persist_to_workspace:
          root: .
          paths:
            - dist/*
  prepare:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - attach_workspace:
         at: .
      - run: ls -al
      - run:
          name: Get gh-pages
          command: |
            git clone -b gh-pages https://github.com/shopizer-ecommerce/documentation.git
      - run: ls -lR

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - prepare:
          requires:
            - build